#ifndef ICE_FISHING_COMMON_DEFS_H
#define ICE_FISHING_COMMON_DEFS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define WATER_Y WINDOW_HEIGHT / 3.0
#define PLAYER_X WINDOW_WIDTH * 3.0 / 4.0
#define HOOK_X PLAYER_X - 180

#endif
