#ifndef COMMON_DEFS_H
#define COMMON_DEFS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define WATER_Y WINDOW_HEIGHT / 3.0
#define PLAYER_X WINDOW_WIDTH * 2.0 / 3.0 + 20
#define HOOK_X PLAYER_X - 100

#endif
